### ISSUE TITLE
`connect` does not work correctly 

### ISSUE THREAD

**Issue by HellWolf93** [djipidi/graphene_django_crud#2]
Using this models:
```python
class Product(models.Model):
    pass

class Image(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE, null=True, blank=True)
```
If I try to create a product with the following query:
```graphql
mutation {
  createProduct(
    input: {
      images: {
        connect: {
          id: {
            in: [4, 5]
          }
        },
      },
    }
  ) {
    ok
}
```
it fails with `get() returned more than one Image -- it returned 2!`.

Any idea on how to achieve this? I am trying not to have to update the images in another query after creating the product.

Thanks.

**Comment by djipidi** [comment]
The WhereInput of the ConnectInput accepts a single instance of your model. 

But you can do this:
```graphql
mutation {
    createProduct(
        input: {
             images: {
                 connect: [
                      { id: { exact : 4 } },
                      { id: { exact : 5 } },
                ]
             }, 
        }
    )
   { ok }
}
```
Best regards

**Comment by HellWolf93** [comment]
It works like a charm. Thank you very much. You have made it really easy to implement CRUD operations with graphene-django.
