### ISSUE TITLE
Allow subclass `DjangoCRUDObjectType`

### ISSUE THREAD

**Issue by HellWolf93** [djipidi/graphene_django_crud#3]
I need to handle users permissions on mutate, create, update and delete methods, but I dont want to define those methods for each type.

Instead, I thought about subclassing `DjangoCRUDObjectType` and add some fields to the Meta class (create_perms, update_perms, ...). Then in my `CustomCRUDObjectType(DjangoCRUDObjectType)` I could declare the mutation methods and do something like this:
```python
@classmethod
def create(cls, parent, info, instance, data, *args, **kwargs):
    authorized = all(info.context.user.has_perm(perm)
                     for perm in cls._meta.create_perms)
    if not authorized:
        raise GraphQLError('not authorized')
    return super().create(parent, info, instance, data, *args, **kwargs)
```
And use this class instead of `DjangoCRUDObjectType`.

However, this is not currently possible, because `DjangoCRUDObjectType` does not accepts a _meta param on its `__init_subclass_with_meta__`, and instead creates one from scratch.

**Solution**
I believe it is possible to do a minor refactor on `__init_subclass_with_meta__` to receive a _meta param, and then do something like this:
```python
if not _meta:
    _meta = DjangoCRUDObjectTypeOptions(cls)
```

Do you think that this is possible? I'm willing to open a PR if time is an issue, although this seems to be a pretty quick fix.

**Comment by djipidi** [comment]
Thank you for your contribution

I agree that the inability to have a subclass is a problem.
I like your way, I would like your PR.

Best regards
